//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Collections.Specialized;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace UnityLauncherPro.Properties
{
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("880")]
        public int windowWidth
        {
            get
            {
                return ((int)(this["windowWidth"]));
            }
            set
            {
                this["windowWidth"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("650")]
        public int windowHeight
        {
            get
            {
                return ((int)(this["windowHeight"]));
            }
            set
            {
                this["windowHeight"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool minimizeToTaskbar
        {
            get
            {
                return ((bool)(this["minimizeToTaskbar"]));
            }
            set
            {
                this["minimizeToTaskbar"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool registerExplorerMenu
        {
            get
            {
                return ((bool)(this["registerExplorerMenu"]));
            }
            set
            {
                this["registerExplorerMenu"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool closeAfterProject
        {
            get
            {
                return ((bool)(this["closeAfterProject"]));
            }
            set
            {
                this["closeAfterProject"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool closeAfterExplorer
        {
            get
            {
                return ((bool)(this["closeAfterExplorer"]));
            }
            set
            {
                this["closeAfterExplorer"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool showArgumentsColumn
        {
            get
            {
                return ((bool)(this["showArgumentsColumn"]));
            }
            set
            {
                this["showArgumentsColumn"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool showGitBranchColumn
        {
            get
            {
                return ((bool)(this["showGitBranchColumn"]));
            }
            set
            {
                this["showGitBranchColumn"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public int[] gridColumnWidths
        {
            get
            {
                return ((int[])(this["gridColumnWidths"]));
            }
            set
            {
                this["gridColumnWidths"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool showProjectsMissingFolder
        {
            get
            {
                return ((bool)(this["showProjectsMissingFolder"]));
            }
            set
            {
                this["showProjectsMissingFolder"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AllowSingleInstanceOnly
        {
            get
            {
                return ((bool)(this["AllowSingleInstanceOnly"]));
            }
            set
            {
                this["AllowSingleInstanceOnly"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string preferredVersion
        {
            get
            {
                return ((string)(this["preferredVersion"]));
            }
            set
            {
                this["preferredVersion"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string newProjectsRoot
        {
            get
            {
                return ((string)(this["newProjectsRoot"]));
            }
            set
            {
                this["newProjectsRoot"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool askNameForQuickProject
        {
            get
            {
                return ((bool)(this["askNameForQuickProject"]));
            }
            set
            {
                this["askNameForQuickProject"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool enableProjectRename
        {
            get
            {
                return ((bool)(this["enableProjectRename"]));
            }
            set
            {
                this["enableProjectRename"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool streamerMode
        {
            get
            {
                return ((bool)(this["streamerMode"]));
            }
            set
            {
                this["streamerMode"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool showTargetPlatform
        {
            get
            {
                return ((bool)(this["showTargetPlatform"]));
            }
            set
            {
                this["showTargetPlatform"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string webglBuildPath
        {
            get
            {
                return ((string)(this["webglBuildPath"]));
            }
            set
            {
                this["webglBuildPath"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool useCustomTheme
        {
            get
            {
                return ((bool)(this["useCustomTheme"]));
            }
            set
            {
                this["useCustomTheme"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("theme.ini")]
        public string themeFile
        {
            get
            {
                return ((string)(this["themeFile"]));
            }
            set
            {
                this["themeFile"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool enablePlatformSelection
        {
            get
            {
                return ((bool)(this["enablePlatformSelection"]));
            }
            set
            {
                this["enablePlatformSelection"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool runAutomatically
        {
            get
            {
                return ((bool)(this["runAutomatically"]));
            }
            set
            {
                this["runAutomatically"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool useCustomLastModified
        {
            get
            {
                return ((bool)(this["useCustomLastModified"]));
            }
            set
            {
                this["useCustomLastModified"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("dd/MM/yyyy HH:mm:ss")]
        public string customDateFormat
        {
            get
            {
                return ((string)(this["customDateFormat"]));
            }
            set
            {
                this["customDateFormat"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool useHumandFriendlyLastModified
        {
            get
            {
                return ((bool)(this["useHumandFriendlyLastModified"]));
            }
            set
            {
                this["useHumandFriendlyLastModified"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public int[] recentColumnsOrder
        {
            get
            {
                return ((int[])(this["recentColumnsOrder"]));
            }
            set
            {
                this["recentColumnsOrder"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public int[] gridColumnWidthsBuildReport
        {
            get
            {
                return ((int[])(this["gridColumnWidthsBuildReport"]));
            }
            set
            {
                this["gridColumnWidthsBuildReport"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool runAutomaticallyMinimized
        {
            get
            {
                return ((bool)(this["runAutomaticallyMinimized"]));
            }
            set
            {
                this["runAutomaticallyMinimized"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-s Unity ActivityManager PackageManager dalvikvm DEBUG -v color")]
        public string adbLogCatArgs
        {
            get
            {
                return ((string)(this["adbLogCatArgs"]));
            }
            set
            {
                this["adbLogCatArgs"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int projectName
        {
            get
            {
                return ((int)(this["projectName"]));
            }
            set
            {
                this["projectName"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string templatePackagesFolder
        {
            get
            {
                return ((string)(this["templatePackagesFolder"]));
            }
            set
            {
                this["templatePackagesFolder"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("win64")]
        public string newProjectPlatform
        {
            get
            {
                return ((string)(this["newProjectPlatform"]));
            }
            set
            {
                this["newProjectPlatform"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool searchProjectPathAlso
        {
            get
            {
                return ((bool)(this["searchProjectPathAlso"]));
            }
            set
            {
                this["searchProjectPathAlso"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool checkPlasticBranch
        {
            get
            {
                return ((bool)(this["checkPlasticBranch"]));
            }
            set
            {
                this["checkPlasticBranch"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string shortcutBatchFileFolder
        {
            get
            {
                return ((string)(this["shortcutBatchFileFolder"]));
            }
            set
            {
                this["shortcutBatchFileFolder"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
                             "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
                             "tring>C:\\Program Files\\</string>\r\n</ArrayOfString>")]
        public StringCollection rootFolders
        {
            get
            {
                return ((StringCollection)(this["rootFolders"]));
            }
            set
            {
                this["rootFolders"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool useInitScript
        {
            get
            {
                return ((bool)(this["useInitScript"]));
            }
            set
            {
                this["useInitScript"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("50000")]
        public int webglPort
        {
            get
            {
                return ((int)(this["webglPort"]));
            }
            set
            {
                this["webglPort"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
                             "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public StringCollection projectPaths
        {
            get
            {
                return ((StringCollection)(this["projectPaths"]));
            }
            set
            {
                this["projectPaths"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool override40ProjectCount
        {
            get
            {
                return ((bool)(this["override40ProjectCount"]));
            }
            set
            {
                this["override40ProjectCount"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("50")]
        public int maxProjectCount
        {
            get
            {
                return ((int)(this["maxProjectCount"]));
            }
            set
            {
                this["maxProjectCount"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("https://raw.githubusercontent.com/unitycoder/UnityInitializeProject/main/Assets/E" +
                             "ditor/InitializeProject.cs")]
        public string customInitFileURL
        {
            get
            {
                return ((string)(this["customInitFileURL"]));
            }
            set
            {
                this["customInitFileURL"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string currentSortColumn
        {
            get
            {
                return ((string)(this["currentSortColumn"]));
            }
            set
            {
                this["currentSortColumn"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool currentSortDirectionAscending
        {
            get
            {
                return ((bool)(this["currentSortDirectionAscending"]));
            }
            set
            {
                this["currentSortDirectionAscending"] = value;
            }
        }

        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool useAlphaReleaseNotes
        {
            get
            {
                return ((bool)(this["useAlphaReleaseNotes"]));
            }
            set
            {
                this["useAlphaReleaseNotes"] = value;
            }
        }
    }
}
